[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.81.0"
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "make theme synchronize && hugo -b $URL"

[context.deploy-preview]
  command = "make theme synchronize && hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "make theme synchronize && hugo -b $DEPLOY_PRIME_URL --gc --minify"
